Update adafruit_rockblock.py
adafruit/Adafruit_CircuitPython_RockBlock pull request #11
Opened 2020-10-07 02:45 UTC by graemerae

Added a function to return Signal Strength
(note previous PR was mangled because of an indent issue on my browser)

2020-10-07 03:03 UTC, dherrada commented
So, the indentation looks good, but it's failing black. I'd start by installing black with pip. Then, run this in the repository folder:
`black --target-version=py35 .`

2020-10-14 17:07 UTC, caternuson requested changes

2020-10-14 17:07 UTC, caternuson commented on adafruit_rockblock.py
> +    def signalStrength(self):
Rename to `signal_quality` to avoid use of camel case and better match parameter name to ISU AT Command Reference.

2020-10-14 17:18 UTC, caternuson commented
@graemerae Keep trying. This is a really good PR to get more familiar with the general PR process. If you commit and push the changes to your PR branch, the updates will automatically be seen here and the checks will run again. No need for a new separate PR.

2021-01-06 17:00 UTC, kattni commented
@graemerae Are you still interested in working on this?

2021-01-06 17:03 UTC, graemerae commented
If i can figure out how to do a pull request, yes.



> On Jan 6, 2021, at 9:01 AM, Kattni <notifications@github.com> wrote:
> 
> 
> @graemerae <https://github.com/graemerae> Are you still interested in working on this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/adafruit/Adafruit_CircuitPython_RockBlock/pull/11#issuecomment-755428004>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA4L575V7MGJ4C5FI4OFFSDSYSJM5ANCNFSM4SGZV3QA>.
>

2021-01-06 17:06 UTC, kattni commented
@graemerae You can push to this PR branch and it will update this PR. I'm guessing you did it through GitHub though, which makes editing it a little more interesting. If you'd like to, you can make the changes and make a new PR with all the changes. Or, we have a guide on Contributing with Git and GitHub [here](https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github) that might help you figure out running things locally. If you're not already on the [Adafruit Discord](https://adafru.it/discord), we're also available there for questions.

2021-01-12 17:27 UTC, caternuson commented
Closing. This was added with #15 and released with 1.2.0. Look for the new `signal_quality` property.

2021-01-12 17:27 UTC, closed without merging