add accumulated energy monitor feature (AT+GEMON)
adafruit/Adafruit_CircuitPython_RockBlock pull request #16
Opened 2021-01-12 21:39 UTC by zunkworks

I've added code to query the modem's accumulated energy monitor, +GEMON which returns an estimate of the microamp hours the modem has consumed. I think it would be very useful for anyone running off batteries/solar/etc. 

However the software revision I have on several modems does not support this. I do have an older modem that does support it, and RockBlock support shows it working on a newer revision than what I have. I've tested on both revisions.

Documented in code with "Note: Call Processor Version: TA12003 is known to not support the AT+GEMON energy monitor command. It is however known to work on TA19002 (newer) and TA12003 (older). You may use the revision function to determine which version you have. Function will return None if modem cannot retrieve the accumulated energy usage estimate."

This code returns None if the modem returns ERROR when issuing the +GEMON command. It raises a RuntimeError if the setter is unable to preset the accumulator value.

2021-01-12 23:51 UTC, caternuson commented
It's not super obvious given the generic name, but this library is really for the RockBLOCK 9603:
https://www.adafruit.com/product/4521

There's a table summarizing command implementation by product in the AT command reference:
https://www.rock7.com/downloads/IRDM_ISU_ATCommandReferenceMAN0009_Rev2.0_ATCOMM_Oct2012.pdf

Does that match what you are finding w.r.t. certain modems working / not working?
![gemon](https://user-images.githubusercontent.com/8755041/104388266-b8d6cf80-54ed-11eb-84e1-3d735217bb86.png)

2021-01-13 00:31 UTC, zunkworks commented
The TA12003 following 9603 is the software revision running on the 9603 modem and according to the "Iridium 9603/9603N SBD Transceiver Developer’s Guide REVISION 3.1" it can be upgraded, however the upgrade tool and firmware images do not seem to be publicly available. (more specifically the revision can be found by issuing the revision command and can be found there as the "Call Processor Version" and "BOOT Version".)

I have a support ticket in with RockBlock and have been discussing this issue with one of their support personnel. They tested on a 9603 with revision TA19002 and the +GEMON function works. I tested on TA16005 and it does not work. I also tested on TA12003 and the function works. I'm not sure which revisions Adafruit has sold or is selling, but I do have a new one from Adafruit coming in later this week that I can test on.

I also just realized my comment about which revision it does not work on is wrong. It should state that it's known to not function on revision TA16005 instead of TA12003.

2021-01-13 17:13 UTC, zunkworks commented
RockBlock support confirmed +GEMON was removed from TA16005. They sent me the update utility for TA19002 and the corresponding release notes which state that +GEMON was removed in TA16005. The release notes do not state when it was added back but I can confirm it does work in TA19002. There was one interim release TA17006, whose release notes state:
 
> Changed the software bootloader to provide compatibility with alternate flash memory devices. Ensures production continuity if issues arise in the supply chain for this part. Functionality of the product is unchanged as compared to TA16005." 

Which makes me think that revision too probably does not support +GEMON. 

There are revisions TA12003, TA13001, TA14001, TA15002 prior to TA16005 which should work with +GEMON. Unknown might be TA11002, TA11001 and the first release for the 9603 TA10003, because those are all prior to the AT command documentation that we can easily find online. 

There also appears to be a newer release TA20003 but I've not tested this revision (it's not what RockBlock sent me). 

I'm not sure which revision is currently shipping from Adafruit but I'll know by the end of this week and comment back here with the revision when I do.

2021-01-14 23:18 UTC, zunkworks commented
Version currently shipping from Adafruit is TA19002, +GEMON works.

2021-01-15 16:47 UTC, caternuson requested changes

2021-01-15 16:47 UTC, caternuson commented on adafruit_rockblock.py
> +        """Report the current accumulated energy usage estimate in microamp hours.
Suggest removing "Report" from first line of doc string and just make it say "The current accumulated...".

2021-01-15 16:48 UTC, caternuson commented
OK, we can add this. One minor suggestion for a docstring tweak.

2021-01-21 00:05 UTC, caternuson commented
Sorry. Lost track of this one for some reason. This looks good! Thanks again for the update.

2021-01-21 00:05 UTC, caternuson approved these changes

2021-01-21 00:05 UTC, merged